Added one-way anova + fix lavaan issue
jamovi/jmv pull request #201
Opened 2018-09-16 04:02 UTC by raviselker

2018-09-16 08:20 UTC, jonathon-love requested changes
Could you separate the lavaan and one-way anova into two commits?

And add references from the commits to the respective issues?

2018-09-16 08:20 UTC, jonathon-love commented on R/anovaonew.b.R
> +                image$setState(results[[dep]]$residuals)
storing one point per row in the data set doesn't scale. if a data set has millions of rows, then that's megabytes of data which is being serialized, and deserialized (slow). so calculate the residuals *in* the plot function itself, like here:

https://github.com/jamovi/jmv/blob/master/R/ttestis.b.R#L501

2018-09-16 08:20 UTC, jonathon-love commented on jamovi/anovaonew.a.yaml
> +      title: Fisher's
Is there space for `Fisher's (assume equal variances)`? or `Assume equal variances (Fisher's)`?

We try and refer to things by what they're used for (i.e. in our menus)

2018-09-16 08:21 UTC, jonathon-love commented
oh wait, i see they are separate, and i see you have referenced the issues appropriately.

2018-09-16 17:50 UTC, raviselker commented on R/anovaonew.b.R
> +                image$setState(results[[dep]]$residuals)
That means that I would also have to do the data cleaning, and fitting the model again in the plot function...

2018-09-16 17:58 UTC, raviselker commented on jamovi/anovaonew.a.yaml
> +      title: Fisher's
How about this:
![screenshot from 2018-09-16 10-57-51](https://user-images.githubusercontent.com/4669197/45599377-6594f680-b99f-11e8-88f4-e36c6366a281.png)

2018-09-16 18:04 UTC, raviselker commented on jamovi/anovaonew.a.yaml
> +      title: Fisher's
But then it makes more sense to let them be radio buttons :confused:

2018-09-16 18:05 UTC, raviselker commented
Gotta pay attention @jonathon-love

2018-09-16 22:23 UTC, jonathon-love commented on R/anovaonew.b.R
> +                image$setState(results[[dep]]$residuals)
yup.. which is probably all cheaper than disk io - even for small data sets.

you can cache the fitted model (assign it to something `private$.model`) in `.run` (but your plotting code shouldn't assume that `.run` has been called. so you probably want a `.initModel()` function that you call from both `.run()` and your plot function)

2018-09-16 22:24 UTC, jonathon-love commented on R/anovaonew.b.R
> +                image$setState(results[[dep]]$residuals)
yup.. which is probably all cheaper than disk io - even for small data sets.

you can cache the fitted model (assign it to something `private$.model`) in `.run` (but your plotting code shouldn't assume that `.run` has been called. so you probably want a `.initModel()` function that you call from both `.run()` and your plot function)

2018-09-16 22:26 UTC, jonathon-love commented on jamovi/anovaonew.a.yaml
> +      title: Fisher's
Always try and avoid 'yes', 'no' questions.

Something more like:

```
    Variances
        [  ] Assume equal (Fisher's)
        [  ] Don't assume (Welch's)
```

2018-09-16 22:27 UTC, jonathon-love commented
oh well, i was looking on my phone, and it certainly looks like all commits are one there.

2018-09-16 22:38 UTC, jonathon-love commented
i cherry-picked the CFA and t-test commits.

2018-09-17 00:12 UTC, raviselker commented on R/anovaonew.b.R
> +                image$setState(results[[dep]]$residuals)
But the fitted model contains all the residuals. So with a big data set, this would also be a big object.

2018-09-17 02:23 UTC, raviselker commented on jamovi/anovaonew.a.yaml
> +      title: Fisher's
Don't assume variances?

2018-09-17 03:47 UTC, jonathon-love commented on jamovi/anovaonew.a.yaml
> +      title: Fisher's
Don't assume equal?

2018-09-17 03:55 UTC, jonathon-love commented on R/anovaonew.b.R
> +                image$setState(results[[dep]]$residuals)
yup, but the private members of an analysis object are not serialized.

2018-09-17 03:57 UTC, jonathon-love commented on R/anovaonew.b.R
> +                image$setState(results[[dep]]$residuals)
what you assign to the `state` gets serialised and deserialised each time the analysis runs (or when a plot needs to be generated). so we want to keep this smallish.

2018-09-17 03:58 UTC, raviselker commented on R/anovaonew.b.R
> +                image$setState(results[[dep]]$residuals)
k, so I can just store the residuals into `private$.residuals`?

2018-09-17 04:02 UTC, jonathon-love commented on R/anovaonew.b.R
> +                image$setState(results[[dep]]$residuals)
yup, but if a plot is requested after the analysis has been run, `.run()` may not be run (i.e. when a person copies a plot to the clipboard), so your plotting code needs to be able to generate residuals if they're not there.

2018-09-17 07:28 UTC, jonathon-love commented
the `clearWith` properties of plots look like they need some attention... they refresh when unrelated options change.

2018-09-17 18:31 UTC, raviselker commented
Which options are you talking about? Everything seems to work fine over here.

2018-09-17 21:45 UTC, jonathon-love commented
ah yup, the changes i made to the `key`s has broken it.

2018-09-18 02:27 UTC, jonathon-love commented
merged

2018-09-18 02:27 UTC, closed without merging