Descriptives: Added bar plots for continuous vars
jamovi/jmv pull request #224
Opened 2019-05-14 04:06 UTC by jonathon-love

I limited it to a single 'split variable' for the time being.

jonathon

2019-07-18 13:06 UTC, raviselker requested changes
So if you change a couple of things you can easily make the bar plot facet functionality work for continuous vars

2019-07-18 13:06 UTC, raviselker commented on R/descriptives.b.R
> +                            nSplits <- 1
Change both `nSplits` to 3

2019-07-18 13:06 UTC, raviselker commented on R/descriptives.b.R
> -            if (length(splitBy) > 1)
Leave this in (this should work for both categorical and continuous variables)

2019-07-18 13:06 UTC, raviselker commented on R/descriptives.b.R
> -            if (length(splitBy) == 2) {
Leave this statement in

2019-07-20 05:47 UTC, jonathon-love commented
github is clearly confused, because there should only be two commits here, but whatevs.

https://github.com/jonathon-love/jmv

2019-08-16 08:33 UTC, raviselker approved these changes

2019-08-17 01:09 UTC, merged