Percentiles added to descriptives
jamovi/jmv pull request #275
Opened 2020-11-07 19:49 UTC by victor-moreno

Currently you can get quantile up to 10 groups in descriptives. I needed the 5th and 95th percentiles, so I propose a new option to generate a comma-delimited list of arbitrary percentiles.
The TextBox is small and I don't know if it could be made larger. 
I have set as default 0.05,0.95 to indicate that any percentile list can be used.

2020-11-07 21:06 UTC, jonathon-love commented
i wonder if we shouldn't default this to 0.25, 0.5, and 0.75, and then we can ditch the quantiles option.

2020-11-07 21:07 UTC, jonathon-love commented
oh, this looks great btw :)

2020-11-07 21:54 UTC, victor-moreno commented
I agree, the quartiles are redundant if it defaults to 0.25,0.5,0.75
Changing it should be careful because the cutpoints check the quartiles to avoid redundancy

2020-11-08 04:01 UTC, jonathon-love commented
cool, well ravi's jamovi day is tuesday, so if you can get it done before then, it will save you waiting a week for him :)

2020-11-08 20:33 UTC, jonathon-love commented
you definitely take an iterative approach, victor :P

2020-11-09 06:48 UTC, victor-moreno commented
Hi,
The last changes remove the quartiles and check percentiles to remove redundant ones if the same quantiles have been selected before.

2020-11-10 11:19 UTC, raviselker requested changes
It's looking good. Check out the comments for a couple of improvements that I think would be nice to add.

2020-11-10 11:19 UTC, raviselker commented on jamovi/descriptives.u.yaml
> +                        enable: (pcVal)
It's nicer if the width of the textbox is a bit wider. You can just add `width: large` here

2020-11-10 11:19 UTC, raviselker commented on R/descriptives.b.R
> +                pcValues <- as.numeric(unlist(strsplit(self$options$pcValues,",")))
I think it's nicer if the R users of `jmv` can just use a numeric vector to specify the percentile values (so `c(0.25, 0.5, 0.75)`), which means you should only do this stringsplit if `pcValues` is a string.

2020-11-10 11:19 UTC, raviselker commented on jamovi/descriptives.a.yaml
> +      default: "0.25,0.5,0.75"
Why are you using proportions instead of percentages here? I would expect this to be "25, 50, 75"

2020-11-10 11:19 UTC, raviselker commented on R/descriptives.b.R
> +                    npcValues <- length(pcValues)
You do this a couple of times in the code, so I would maybe move this to a separate method (e.g., .convertPcValues) that stores these values into member values (see for instance line 18 in `descriptives.b.R`).

2020-11-10 12:33 UTC, victor-moreno commented on R/descriptives.b.R
> +                pcValues <- as.numeric(unlist(strsplit(self$options$pcValues,",")))
I thought pcValues will always be a string if it is so defined in u.yaml (comment before).
I will check if it is a numeric vector and avoid this split in that case

2020-11-10 12:37 UTC, victor-moreno commented on jamovi/descriptives.a.yaml
> +      default: "0.25,0.5,0.75"
This is to make it consistent with the cutoffs that will be passed to quantile(x, probs=
I can change that to percentages and divide by 100 in the code if you think it is better

2020-11-10 14:48 UTC, raviselker requested changes
At the moment the unit test for this analysis (tests/testthat/testdescriptives.R) doesn't work anymore because it still uses the `quart` parameter. So you need to change this as well

2020-11-10 14:48 UTC, raviselker commented on jamovi/descriptives.a.yaml
> +    - name: pcVal
I would rename this option to `pc`. It's easy to mix up `pcVal` and `pcValues`.

2020-11-10 14:48 UTC, raviselker commented on R/descriptives.b.R
> +            pcValues[pcValues < 0 | pcValues > 100] <- NA
At the moment I'm getting the following error when including a pcValue > 100:
```Error in quantile.default(column, pcValues) : 'probs' outside [0,1]```

I would try to catch the error and give an informative error message instead (e.g., "one or more "pcValues" have a value below 0 or above a 100. All "pcValues" need to be between 0 and 100.)

2020-11-10 15:45 UTC, victor-moreno commented on jamovi/descriptives.a.yaml
> +    - name: pcVal
OK I will do a global rename

2020-11-10 15:46 UTC, victor-moreno commented on R/descriptives.b.R
> +            pcValues[pcValues < 0 | pcValues > 100] <- NA
should be pcValues >1] once it is divided by 100. I have fixed that

2020-11-10 16:50 UTC, victor-moreno commented on R/descriptives.b.R
> +            pcValues[pcValues < 0 | pcValues > 100] <- NA
I have changed the default pcValues in function descriptives (descriptives.h.R), but the change is overwritten and the default value for pcValues in descriptives shows as "25,50,75". Use of c(25,50,75) works in R

args(descriptives)
function (data, vars, splitBy = NULL, freq = FALSE, hist = FALSE,
    dens = FALSE, bar = FALSE, barCounts = FALSE, box = FALSE,
    violin = FALSE, dot = FALSE, dotType = "jitter", qq = FALSE,
    n = TRUE, missing = TRUE, mean = TRUE, median = TRUE, mode = FALSE,
    sum = FALSE, sd = TRUE, variance = FALSE, range = FALSE,
    min = TRUE, max = TRUE, se = FALSE, skew = FALSE, kurt = FALSE,
    sw = FALSE, pcEqGr = FALSE, pcNEqGr = 4, pc = FALSE, pcValues = **"25,50,75"**,
    formula)

I can't find where I should change this.

2020-11-11 08:51 UTC, raviselker commented on R/descriptives.b.R
> +            pcValues[pcValues < 0 | pcValues > 100] <- NA
Maybe @jonathon-love can chime in?

2020-11-11 08:51 UTC, raviselker commented
> At the moment the unit test for this analysis (tests/testthat/testdescriptives.R) doesn't work anymore because it still uses the `quart` parameter. So you need to change this as well

Don't forget to change the unit test :)

2020-11-11 09:55 UTC, jonathon-love commented on R/descriptives.b.R
> +            pcValues[pcValues < 0 | pcValues > 100] <- NA
hey,

i'm not sure i understand the problem. the default value of "25, 50, 75" is correct?

with thanks

2020-11-11 12:06 UTC, victor-moreno commented on R/descriptives.b.R
> +            pcValues[pcValues < 0 | pcValues > 100] <- NA
This is not essential, since both jamovi and jmv R package work as expected when pcValues is defined as character "25,50,75", but probably would be better to set the default as a numeric vector c(25,50,75) in the function to be used from R.

Although I have changed the default value in function descriptives, file descriptives.h.R, I think this file is regenerated and changes have no effect on the actual code in the compiled jmv package. I don't know how the function descriptives is generated from the code to set as default for pcValues=c(25,50,75)

2020-11-11 14:02 UTC, victor-moreno commented
I have revised tests/testthat/testdescriptives.R

2020-11-11 16:12 UTC, raviselker commented on R/descriptives.b.R
> +            pcValues[pcValues < 0 | pcValues > 100] <- NA
Yeah, it is indeed regenerated so if you commit the version of `descriptives.h.R` that you get after running `jmvtools::install()` everything is good and I'll approve the pull request. Good work!

2020-11-11 16:39 UTC, victor-moreno commented on R/descriptives.b.R
> +            pcValues[pcValues < 0 | pcValues > 100] <- NA
Done, I have left the code as of descriptives.h.R as generated

2020-11-11 16:41 UTC, raviselker approved these changes
It's ready to merge. I'll leave it to @jonathon-love cause we probably want to squash all those commits into one.

2020-11-11 20:39 UTC, jonathon-love commented on R/descriptives.b.R
> +            pcValues[pcValues < 0 | pcValues > 100] <- NA
> probably would be better to set the default as a numeric vector c(25,50,75)

ah yeah, this is a limitation at this time ... (and probably not worth the effort on my part).

2020-11-12 08:05 UTC, merged

2020-11-12 08:05 UTC, jonathon-love commented
thanks victor! this is really great work!