Bug/jmv 45 lin regression not working 10000 cases
jamovi/jmv pull request #276
Opened 2020-12-15 22:37 UTC by raviselker

Fixes jamovi/jamovi-fun-todo-list#45

2020-12-16 00:22 UTC, jonathon-love requested changes

2020-12-16 00:22 UTC, jonathon-love commented on R/linreg.b.R
> +        .computeModels = function(data, model = NULL, scaled = FALSE) {
could this be `modelNo` rather than `model`? `model` makes me expect the model object.

2020-12-16 00:22 UTC, jonathon-love commented on R/linreg.b.R
> +            model <- private$.computeModels(data, model=image$state)[[1]]
you're better off assigning the models to (something like) `private$.models` in the `.run()` phase, and only computing them here if `private$.models` is unassigned. when the analysis is run, the same analysis object is used to create all the plots. it's only when the user, say, exports an image, that the plot function is called without `.run()` being called first.

you could go further of course, have a caching active binding, etc.

2020-12-16 21:33 UTC, raviselker commented on R/linreg.b.R
> +            model <- private$.computeModels(data, model=image$state)[[1]]
So something like: 
```        
models = function() {

            if (! is.null(private$.models))
                return(private$.models)

            data <- private$.cleanData()
            models <- private$.computeModels(data)

            return(models)
},
```

2020-12-17 22:19 UTC, raviselker commented on R/linreg.b.R
> +        .computeModels = function(data, model = NULL, scaled = FALSE) {
Fixed

2020-12-17 22:19 UTC, raviselker commented on R/linreg.b.R
> +            model <- private$.computeModels(data, model=image$state)[[1]]
Fixed this by a major refactoring

2020-12-18 00:23 UTC, jonathon-love commented
just a heads up ... i think the next time we push jmv to CRAN, CRAN will insist that all these active bindings are documents :/

2020-12-18 00:24 UTC, merged