conttables Mantel-Haenszel trend test
jamovi/jmv pull request #282
Opened 2021-01-02 12:28 UTC by victor-moreno

This contains only the Mantel-Haenszel trend test for conttables
Victor

2021-01-12 12:52 UTC, raviselker requested changes
Hi Victor, Excellent addition to the conttables! I added a couple of comments, but after you address these, I'll accept this PR.

2021-01-12 12:52 UTC, raviselker commented on R/conttables.b.R
> +                    if (mhchi2 == -1)
I can get the following error to appear:
```Error in if (mhchi2 == -1) mh$addFootnote(rowNo = othRowNo, "chi2", "One variable must be binary") : 
  missing value where TRUE/FALSE needed 
```

You can run the following code to reproduce (works fine with `mh = FALSE`):
```
set.seed(1337)
data <- data.frame(
    A = sample(letters[1:2], 100, replace = TRUE),
    B = sample(letters[1:3], 100, replace = TRUE),
    C = sample(letters[1:16], 100, replace = TRUE)
)

jmv::contTables(formula = ~ A:B:C, data = data, mh = TRUE)
```

2021-01-12 12:52 UTC, raviselker commented on R/conttables.b.R
> +                    else
If the content of one or more of the if (or else) statement contains multiple lines, always use parentheses for clearity. So here you can either make one line of the `values <- list(....)` statement or you can add parentheses to both the if and the else.

2021-01-12 12:52 UTC, raviselker commented on R/conttables.b.R
> +
Remove empty line

2021-01-12 12:52 UTC, raviselker commented on jamovi/conttables.a.yaml
> +    - name: mh
At the moment the option for Mantel-Haenszel is displayed underneath the "ordinal" heading. Looking at the wikipedia it seems you can also use it for nominal data. If this is the case, please move it to the "nominal" heading.

2021-01-12 12:52 UTC, raviselker commented on jamovi/conttables.r.yaml
> +      title: Mantel-Haenszel test for trend
Title of tables in header case. So: "Mantel-Haenszel Test for Trend"

2021-01-12 12:52 UTC, raviselker commented on R/conttables.b.R
> +
Remove empty line

2021-01-12 12:52 UTC, raviselker commented on R/conttables.b.R
> +                            if (all(dim(mat))>2)
Add spaces around logical operators. So: `...dim(mat)) > 2....`

2021-01-12 12:52 UTC, raviselker commented on R/conttables.b.R
> +                                mhchi2 <- try((cor(v1, v2)^2)*(sum(df$Freq)-1))
In most cases, surround mathematical operators by spaces. See https://style.tidyverse.org/syntax.html#infix-operators for more information. This whole style guide would be good to go through at some point. Adhering to a good style guide will make code easier to read.

2021-01-12 19:08 UTC, victor-moreno commented on jamovi/conttables.a.yaml
> +    - name: mh
Hi, 
This is the Mantel-Haenszel test for trend and only makes sense for ordinal data. I couldn't find this in wikipedia. Wikipedia refers to a different Cochran-Mantel-Haenszel statistic to calculate an OR pooled over strata of a third categorical variable.

2021-01-12 21:12 UTC, raviselker commented on jamovi/conttables.a.yaml
> +    - name: mh
Ah, I just assumed this was the same statistic. You can ignore this comment then :)

2021-01-12 22:36 UTC, victor-moreno commented on R/conttables.b.R
> +                    if (mhchi2 == -1)
Hi Ravi
I have fixed that, and also have cached two more bugs, one detecting tables >2x2 and other with the footnote, that was not shown because was declared before the output table. Also have formated df as integer.
Together with the coding style fixes, that I appreciate, I think it should be ready now.

2021-01-13 16:53 UTC, victor-moreno commented
Hi, 
I discovered today that vcd package used to calculate log-odds-ratios and from them the OR provide wrong results when there is a zero in the 2x2 table. It should be zero or Inf, but the result is a variable number near to zero or large, but not the correct answer.

```
df <- data.frame(
A = factor(c(0,0,1,1)),
B = factor(c(0,1,0,1)),
count = c(34,76,12,0) )

data <- df[rep(seq_len(nrow(df)), df$count), 1:2]
jmv::contTables(data=data, formula= ~ A:B, logOdds = TRUE, odds = TRUE)

 ──────────────────────────────
   A        0     1     Total
 ──────────────────────────────
   0        34    76      110
   1        12     0       12
   Total    46    76      122
 ──────────────────────────────

                    Value         Lower          Upper
 ────────────────────────────────────────────────────────────
   Log odds ratio     -4.015207      -6.870342    -1.160072
   Odds ratio        0.01803922    0.001038122    0.3134635
────────────────────────────────────────────────────────────
```


I propose to change the code to use fisher.test function, that doesn't require any additional library and provides an exact confidence interval. From that we can calculate the log-OR.

If you agree, I can prepare the changes and profit this PR

2021-01-14 20:34 UTC, raviselker commented
So it looks like vcd applies a continuity correction when there are zero cells:

> **correct:** logical or numeric. Should a continuity correction be applied before computing odds? If TRUE, 0.5 is added to all cells; if numeric (or an array conforming to the data) that value is added to all cells. By default, this not employed unless there are any zero cells in the table, but this correction is often recommended to reduce bias when some frequencies are small (Fleiss, 1981).

Wouldn't this be an adequate solution to the problem of zero count cells?

2021-01-15 09:29 UTC, victor-moreno commented
I have been reading about that and the best answer is not an easy decision. If you need a standard error of the OR or logOR for meta-analysis, then adding 0.5 is required. However, to get only the point estimate and 95% CI the exact method can be used. This paper recommends it whenever possible:
https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.2041-210x.2012.00250.x

I suppose we can leave the code as it is. Perhaps a footnote could be added when there is a zero in the table to warn that the correction was applied.

2021-01-16 12:52 UTC, raviselker approved these changes
It all looks good. And I like the idea for the footnote in case of zero counts. Can you have a look at that?

2021-01-16 14:02 UTC, victor-moreno commented
I have added the footnote. The text is 'Haldane-Ascombe correction applied'. 

I found the reference to the original suggestion of adding 0.5 in the prior to the last paragraph sentence here  https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.2041-210x.2012.00250.x
I think adding the reference is not needed. If you paste Haldane-Ascombe correction in google you get this reference on second position.

Also, I have adde a condition to avoid computing estimators in 2x2 table if table in fact is 2x1 or 1x2 because a row or column is all zeros. Since 0.5 is added to each cell, now you get an artificial result for OR and logOR though the chi-square test is NaN.

2021-01-17 02:41 UTC, jonathon-love reviewed
thanks victor, a couple of suggestions from me now.

2021-01-17 02:41 UTC, jonathon-love commented on R/conttables.b.R
> +                        mh$addFootnote(rowNo=othRowNo, 'chi2', 'Variables must have >=2 categories')
`Variables must have at least two levels`?

2021-01-17 02:41 UTC, jonathon-love commented on R/conttables.b.R
> +                        mh$addFootnote(rowNo=othRowNo, 'chi2', 'One variable must be binary')
`At least one variable must have two levels`?

2021-01-17 09:30 UTC, victor-moreno commented
Done

2021-01-17 09:44 UTC, merged