descriptives - mean dot in box plot
jamovi/jmv pull request #283
Opened 2021-01-02 14:03 UTC by victor-moreno

I have split previous pull requests into pieces.
This adds a dot to box plots with the mean

2021-01-10 11:38 UTC, raviselker commented
Just to give you heads up, I'll review all these pull requests into more detail on Tuesday. Thanks for all the work!

2021-01-12 14:27 UTC, raviselker requested changes
A few small comments, but I like the addition of the mean to the box plots!

2021-01-12 14:27 UTC, raviselker commented on R/descriptives.b.R
> +                    plot <- plot + stat_summary(fun.y=mean, geom="point", shape=22, size=2, color="blue", fill="blue")
I don't really like the blue and it's a bit small. Can you change it to:
```
stat_summary(fun.y=mean, geom="point", shape=15, size=3.5, color=theme$color[1])
```
The `theme$color[1]` makes it use the theme color so that it fits with all the jamovi themes. In this case, it's blackish for all themes :)

2021-01-12 14:27 UTC, raviselker commented on R/descriptives.b.R
> +                    plot <- plot + stat_summary(fun.y=mean, geom="point", shape=22, size=2, color="blue", fill="blue")
Same comment as the previous

2021-01-12 14:27 UTC, raviselker commented on R/descriptives.b.R
> +
Remove the empty line

2021-01-12 14:27 UTC, raviselker commented on jamovi/descriptives.a.yaml
> +    - name: boxmean
We use camelcase, so: `boxMean`

2021-01-12 14:27 UTC, raviselker commented on jamovi/descriptives.a.yaml
> +      title: Add mean
Remove the "Add", the add is always implied in the options (otherwise we would have to add "add" to all the options)

2021-01-12 14:27 UTC, raviselker commented on jamovi/descriptives.u.yaml
> +                name: boxmean
Add the following line underneath here (so that the option is grayed out if box, violin, or dot is not checked:
```
enable: (box || violin || dot)
```

2021-01-13 18:54 UTC, victor-moreno commented
All requests have been fixed and tested

2021-01-14 20:28 UTC, raviselker approved these changes
Looks good! @jonathon-love you can merge this one.

2021-01-14 22:00 UTC, merged