Plots added to conttab
jamovi/jmv pull request #290
Opened 2021-01-31 21:54 UTC by victor-moreno

Hi,
This PR adds barplots to conttables. 
I hope you like it

Victor

2021-02-01 12:33 UTC, victor-moreno commented
Preparing this I have found a difficulty that I would like to ask:
- Can I use duplicate names in optionPart in file.u.yaml? 
I would like to use names like rows or counts that already are used. When I tried, there was no compiler error, but the UI for the analysis was not shown in jamovi
If this is possible, I would like to change optionParts that I had to prefix x or y to avoid duplications.

2021-02-02 03:23 UTC, jonathon-love commented
@dropmann ?

2021-02-02 14:32 UTC, raviselker requested changes
Hi Victor, nice to have this functionality added to the contingency tables! I have a lot of minor comments (I admit, I'm pretty nit-picky 😛 ), and a couple bigger ones, the biggest one being that the `yvar` option for percentages doesn't seem to work.

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +        .initPlot = function() {
Rename to `.initBarPlot`. Also, can you move both `.initBarPlot` and `.barPlot` above the helper functions and give them the `#### Plot functions ----` heading, similar to:https://github.com/jamovi/jmv/blob/b0c20558fb96b9a7d28ad9350a1c21dcb9e9342e/R/linreg.b.R#L838

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +            if (length(layerNames)==1)
Add spaces before and after `==`

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +            else if (length(layerNames)>=2)
Add spaces before and after `==`

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +                image$setSize(width*2, height)
Add spaces before and after `*`

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +                image$setSize(width*2, height*2)
Add spaces before and after `*`

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +            if (length(layerNames)>2)
Add spaces before and after `>`.

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +
Get rid of empty line

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +                data <- untable(data[,c(rowVarName, colVarName, layerNames)], counts=data[,countsName])
Add spaces after comma: `untable(data[, c(rowVarName, colVarName, layerNames)], counts=data[, countsName])`

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +            formula <- as.formula(paste0("~",paste(c(rowVarName, colVarName, layerNames), collapse="+")))
I think you can use `jmvcore::composeFormula` for this:
```
jmvcore::composeFormula(NULL, c(rowVarName, colVarName, layerNames))
```

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +            counts<-xtabs(formula, data)
Add spaces before and after `<-`

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +                expand[[i]] <- c(base::levels(data[[i]]))
why is there a `c(...)` around the `levels` call?

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +            tab<-expand.grid(expand)
Add spaces before and after <-

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +            tab$counts<-as.numeric(counts)
Add spaces before and after <-

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +                tab$percentages <-as.numeric(props)*100
Add spaces before and after `<-` , `*`, and `==`. Also, add spaces after commas. Also, add brackets for the if statements and for loops to make it a little more readable

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +                layers <- as.formula(paste0(layerNames[1]," ~ ",layerNames[2]))
Add tabs before the if/else statement content (so before `layers...`). Also spaces after the commas

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +                if(length(layerNames)==1)
space after `if`, spaces before and after `==`

2021-02-02 14:32 UTC, raviselker commented on jamovi/conttables.a.yaml
> +    - name: yvar
I would just call this `yaxis` (and xvar `xaxis`).

2021-02-02 14:32 UTC, raviselker commented on jamovi/conttables.a.yaml
> +          title: "Column percentages"
These don't seem to be working properly yet (I expect the bars to be a stacked total of 100%, and nothing changes when I select `Column percentages` instead:
<img width="1331" alt="Screenshot 2021-02-02 at 15 17 01" src="https://user-images.githubusercontent.com/4669197/106613083-18168580-656a-11eb-9d19-9fa1ad8b33db.png">

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +                    geom_col(position=position, width = 0.7)
Can you capitalize the y axis label (so "Counts")

2021-02-02 14:32 UTC, raviselker commented on R/conttables.b.R
> +                    geom_col(position=position, width = 0.7)
Can you add a y axis label that reflects the `% within column/row` instead of the more general `percentages`

2021-02-02 14:32 UTC, raviselker commented on jamovi/conttables.a.yaml
> +      options:
Why no "Percentage of total" option?

2021-02-02 14:32 UTC, raviselker commented on jamovi/conttables.a.yaml
> +          title: "Row percentages"
Maybe change to "Percentage within rows/columns" to be in line with the table.

2021-02-02 14:32 UTC, raviselker commented on jamovi/conttables.a.yaml
> +    - name: xvar
So this could also be changed to xaxis, and title to `X-Axis`

2021-02-02 14:32 UTC, raviselker commented on jamovi/conttables.a.yaml
> +          title: "By side"
Maybe change to "Side by side"

2021-02-02 14:32 UTC, raviselker commented on jamovi/conttables.u.yaml
> +              - type: LayoutBox
General comment: I would put the "Plots" and "Bar Type" sections on the left side, and the "X-Axis" and "Y-Axis" sections on the right side

2021-02-02 14:32 UTC, raviselker commented on jamovi/conttables.u.yaml
> +                    label: Y variable
Change to Y-Axis

2021-02-02 14:32 UTC, raviselker commented on jamovi/conttables.u.yaml
> +                    label: Bar type
Capitalize bot words in title, so "Bar Type"

2021-02-02 19:40 UTC, victor-moreno commented
Hi Ravi,
I have revised all comments, I hope.
Thanks for reviewing

Victor

2021-02-02 20:55 UTC, raviselker requested changes
That was fast! I added two more comments for some final finishing touches. Don't forget to also change the R code where necessary.

2021-02-02 20:55 UTC, raviselker commented on jamovi/conttables.a.yaml
> +            counts (default), row , column or total percentages in bar plot Y axis
I played around with the UI code a bit to make it look like:
<img width="638" alt="Screenshot 2021-02-02 at 21 38 49" src="https://user-images.githubusercontent.com/4669197/106660602-84ac7700-65a0-11eb-827a-7be3f4e6ec12.png">

I think this looks even a bit cleaner than listing all the percentage options as entries of the y-axis option. To do this you need to change this piece of code to:
```
    - name: yaxis
      title: Y-axis
      type: List
      options:
        - name: ycounts
          title: "Counts"
        - name: ypc
          title: "Percentages"
      default: ycounts
      description:
          R: >
            ycounts (default) or ypc. Use respectively `counts` or `percentages`
            for the bar plot y-axis

    - name: yaxisPc
      title: ''
      type: List
      options:
        - name: total_pc
          title: "of total"
        - name: column_pc
          title: "within column"
        - name: row_pc
          title: "within rows"
      default: total_pc
      description:
          R: >
            total_pc (default), column_pc, or row_pc. Use respectively
            percentages `of total`, `within columns`, or `within rows` for the
            bar plot y-axis.
```
And you need to change the u.yaml as well (I added a comment for the change you need to make here), plus fix up a couple of name changes in the R code.

2021-02-02 20:55 UTC, raviselker commented on jamovi/conttables.u.yaml
> +                        optionPart: column_pcts
In order for the earlier mentioned change you need to change this to:
```
                      - type: RadioButton
                        name: ypc
                        optionName: yaxis
                        optionPart: ypc
                        style: inline
                        verticalAlignment: center
                        children:
                          - type: ComboBox
                            name: yaxisPc
                            enable: (ypc)
```

2021-02-03 09:31 UTC, victor-moreno commented
Done! and it looks really nice now.
Thanks
Victor

2021-02-03 11:34 UTC, raviselker approved these changes
Hi Victor, it all looks very good now! Thanks for another great contribution and also for the quick handling of the issues on the PR!

2021-02-03 23:48 UTC, jonathon-love commented
great. let me just chase up @dropmann about your question (because i assume you've used a suboptimal naming scheme to work around this):

> Can I use duplicate names in optionPart in file.u.yaml?

2021-02-04 10:32 UTC, dropmann commented
> 
> 
> Preparing this I have found a difficulty that I would like to ask:
> 
>     * Can I use duplicate names in optionPart in file.u.yaml?
>       I would like to use names like rows or counts that already are used. When I tried, there was no compiler error, but the UI for the analysis was not shown in jamovi
>       If this is possible, I would like to change optionParts that I had to prefix x or y to avoid duplications.

Sorry, it's quite possibly me, but i don't understand the question. Is the question whether or not two controls can use the same optionPart?

2021-02-04 10:43 UTC, jonathon-love commented
maybe you've got two options:

`sortRows`, `sortColumns`

and you can have `sortRows:ascending` and `sortRows:descending` ...

i think victor would like to reuse the same optionPart name, so he can have:

`sortColumns:ascending`, `sortColumns:descending`

as well. otherwise he has to change the values of ascending/descending in a slightly contrived way.

2021-02-04 10:51 UTC, victor-moreno commented
Yes, this example is a good explanation. Also the optionPart name might have been used before as name in other section.

2021-02-04 10:51 UTC, jonathon-love commented
actually, taking a look at the PR, i think victor is wondering if he can have the options:

 - counts
 - yaxis:counts
 
and

 - rows
 - xaxis:rows

and
 
 - cols
 - xaxis:cols

2021-02-04 12:48 UTC, victor-moreno commented
Anyway, with Ravi's suggestions, the PR is complete and functional. This question is more for future

2021-02-04 21:15 UTC, merged