Added Dunn and Conover-Iman tests
jamovi/jmv pull request #329
Opened 2021-12-19 00:21 UTC by MAgojam

Added two tests with p-value correction methods.

2021-12-20 19:08 UTC, raviselker requested changes
Hi @MAgojam, great that you added these extra post-hoc tests for the np anova! I have added some comments to this PR.

2021-12-20 19:08 UTC, raviselker commented on R/anovanp.b.R
> +            pairs       <- private$.genPairs(groupColumn)
So we don't use extra spaces around `=` or `<-`. You'd constantly have to realign everything if you'd make a change in the variable name. Can you fix this throughout the R code?

In general, we try to use [Google's R style guide](https://google.github.io/styleguide/Rguide.html) (which is just the tidyverse style guide with a few additions), so it would be good to go through that (although this guide does allow extra spaces, while we don't 😛)

2021-12-20 19:08 UTC, raviselker commented on R/anovanp.b.R
> +                footnote <- 'This correction is unnecessary for this test.'
Uncomment the translated string, and remove the one below

2021-12-20 19:08 UTC, raviselker commented on R/anovanp.b.R
> +            ## 20211017 - The tests of Dunn and Conover-Iman have been added
Remove this comment.

2021-12-20 19:08 UTC, raviselker commented on R/anovanp.b.R
> +            if (self$options$get("dscfpairs")) {
Can you factor out each type of test into its own function. I also see that there's a lot of overlap in these loops so if you can abstract away pieces of duplicate code even more that's always good (i.e., follow the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself))

2021-12-20 19:08 UTC, raviselker commented on R/anovanp.b.R
> +            #compTables <- self$results$get('comparisons')
Remove comment

2021-12-20 19:08 UTC, raviselker commented on R/anovanp.b.R
> +        .phTest = function(x, g, test, n.g) {
Can you give the parameters more descriptive names? Also, don't use a dot in variable names (only for private functions you can start with a dot), so no `n.g`.

2021-12-20 19:08 UTC, raviselker commented on jamovi/0000.yaml
> +      available to report results across  multiple pairwise comparisons.
```suggestion
      test a single explanatory variable at a time. Conover-Iman and Dunn test
      are available to report results across multiple pairwise comparisons.
```

2021-12-20 19:08 UTC, raviselker commented on jamovi/anovanp.a.yaml
> +        multiple pairwise comparisons.
```suggestion
        time. Conover-Iman and Dunn test are available to report results 
        across multiple pairwise comparisons.
```

2021-12-20 19:08 UTC, raviselker commented on jamovi/anovanp.a.yaml
>              `TRUE` or `FALSE` (default), perform pairwise comparisons
```suggestion
            `TRUE` or `FALSE` (default), perform DSCF pairwise comparisons
```

2021-12-20 19:08 UTC, raviselker commented on jamovi/anovanp.a.yaml
> +            `TRUE` or `FALSE` (default), perform pairwise comparisons
```suggestion
            `TRUE` or `FALSE` (default), perform Dunn's pairwise comparisons
```

2021-12-20 19:08 UTC, raviselker commented on jamovi/anovanp.a.yaml
> +            `TRUE` or `FALSE` (default), perform pairwise comparisons
```suggestion
            `TRUE` or `FALSE` (default), perform Conover's pairwise comparisons
```

2021-12-20 19:08 UTC, raviselker commented on jamovi/anovanp.a.yaml
> +            one or more of `'bonferroni'`, `'sidak'`, `'holm'`
```suggestion
            one or more of `'none'`, `'bonferroni'`, `'sidak'`,  and`'holm'`
```

2021-12-23 14:52 UTC, MAgojam commented on jamovi/0000.yaml
> +      available to report results across  multiple pairwise comparisons.
TA! done

2021-12-23 14:54 UTC, MAgojam commented on jamovi/anovanp.a.yaml
> +        multiple pairwise comparisons.
TA! done

2021-12-23 14:57 UTC, MAgojam commented on jamovi/anovanp.a.yaml
>              `TRUE` or `FALSE` (default), perform pairwise comparisons
TA! done

2021-12-23 15:00 UTC, MAgojam commented on jamovi/anovanp.a.yaml
> +            `TRUE` or `FALSE` (default), perform pairwise comparisons
TA! done

2021-12-23 15:13 UTC, MAgojam commented on jamovi/anovanp.a.yaml
> +            `TRUE` or `FALSE` (default), perform pairwise comparisons
TA!
I would prefer Conover-Iman instead of Conover, because more correct reference to the test used
Conover, W. J. and Iman, R. L. (1979) On multiple-comparisons procedures. Technical Report
LA-7677-MS, Los Alamos Scientific Laboratory.

2021-12-23 15:15 UTC, MAgojam commented on jamovi/anovanp.a.yaml
> +            one or more of `'bonferroni'`, `'sidak'`, `'holm'`
TA! done

2021-12-23 16:39 UTC, MAgojam commented
Ravi,
your important tips and advice have been received and have led me to rewrite a good part of the code.
I still take some time to improve some aspects that do not satisfy me yet.
Thanks again and best wishes.
Maurizio

2022-07-09 11:48 UTC, closed without merging