Update descriptives.b.R
jamovi/jmv pull request #342
Opened 2022-03-16 00:05 UTC by atpinto

Changed the critical value for the confidence interval for the mean. The critical values is now chosen as the quantile from the t-distribution with df=n-1 rather than the quantile from the normal distribution.

2022-03-16 00:07 UTC, atpinto commented
The confidence interval for the mean in the Descriptive statistics command is using the critical values from the normal distribution instead to the t-distribution.  When the sample size is small size, this confidence interval will fail to have the correct coverage because is too narrow.   Given that we are using the sample standard deviation for the calculation of the standard error, the t-distribution should be used for the calculation of the confidence interval for the mean.

The correct confidence interval can be obtained form the t-test command and it will not match the normal-based  confidence interval in the descriptives command.

2022-05-10 17:10 UTC, raviselker requested changes
Sorry for the delay in the review, we were discussing internally for a bit wether we wanted accept this change and we came to the conclusion that it would indeed be better to use a t-distribution. So after the requested changes are applied, I'll approve this PR.

2022-05-10 17:10 UTC, raviselker commented on R/descriptives.b.R
> +                #zQuant <- 1 - ((1 - self$options$ciWidth/100) / 2)
Please remove commented out line
```suggestion
```

2022-05-10 17:10 UTC, raviselker commented on R/descriptives.b.R
> +                #ciDiff <- qnorm(zQuant) * stats[['se']]
Please remove commented out line
```suggestion
```

2022-05-10 17:10 UTC, raviselker commented on R/descriptives.b.R
> +                ciDiff <- qnorm(tQuant, df=length(column)-1 ) * stats[['se']]
Improve formatting
```suggestion
                ciDiff <- qnorm(tQuant, df=length(column) - 1) * stats[['se']]
```

2022-05-10 23:56 UTC, jonathon-love commented
i think we want to add a footnote too @raviselker ? 1. so people are aware of the change. 2. because it's informative to have?

2022-05-17 15:36 UTC, raviselker commented
I fixed up this PR in #348 (there were some other issues with it).

2022-05-17 15:36 UTC, closed without merging