contTables: Fisher's exact test can use a Monte Carlo simulation if the default work area is insufficient
jamovi/jmv pull request #385
Opened 2023-05-26 18:48 UTC by MAgojam

In contTables, if Fisher's exact test returns an error for an insufficient predefined work area, it is retried by activating with a Monte Carlo simulation to determine the p-value.

2023-05-30 04:38 UTC, jonathon-love requested changes
hey mz,

sorry for the delay ... i think you've got some stray content in your .a.yaml file which is showing up in the .h.R file.

otherwise this is looking good.

2023-05-30 04:38 UTC, jonathon-love commented on R/conttables.b.R
> +                    chiSq$addFootnote(rowNo=othRowNo, 'p[fisher]', .('Monte Carlo simulation (B=2000)'))
shift the ` (B=2000)` outside the translation string

2023-05-30 04:38 UTC, jonathon-love commented on R/conttables.b.R
> +                        fish <- try(stats::fisher.test(mat, alternative=Ha, simulate.p.value=TRUE), silent=TRUE)
do you need to specify the `conf.level` here? like the previous call?

2023-05-30 04:38 UTC, jonathon-love commented on R/conttables.h.R
> +                package="magojamtests",
!!

2023-05-30 04:38 UTC, jonathon-love commented on R/conttables.h.R
> +#' Tabella di Contingenza
!!

2023-05-30 04:38 UTC, jonathon-love commented on R/conttables.h.R
> +                    "layers")))
!!

2023-05-30 11:11 UTC, MAgojam commented
> sorry for the delay ... i think you've got some stray content in your .a.yaml file which is showing up in the .h.R file.

Sorry, you're right, I hadn't noticed.
Unfortunately I passed (stupidly) the two conttables files .b.r and .h.r of a module that I use as a clone (so as not to use jmv) in which I am adding a Post-hoc for a significant chi-square with the Standardized and Adjusted residuals (for an upcoming listing proposal for a contingency table) .

2023-05-30 11:17 UTC, MAgojam commented on R/conttables.b.R
> +                    chiSq$addFootnote(rowNo=othRowNo, 'p[fisher]', .('Monte Carlo simulation (B=2000)'))
We can also eliminate `(B=2000)`, considering that it is the default value.

2023-05-30 11:21 UTC, MAgojam commented on R/conttables.b.R
> +                        fish <- try(stats::fisher.test(mat, alternative=Ha, simulate.p.value=TRUE), silent=TRUE)
I can put it back (as in the above) even if it is ignored in the Monte Carlo simulation.

2023-05-30 11:22 UTC, MAgojam commented on R/conttables.h.R
> +#' Tabella di Contingenza
Last reply, below.

2023-05-30 11:23 UTC, MAgojam commented on R/conttables.h.R
> +                    "layers")))
Last reply, below.

2023-05-30 11:29 UTC, jonathon-love commented on R/conttables.b.R
> +                    chiSq$addFootnote(rowNo=othRowNo, 'p[fisher]', .('Monte Carlo simulation (B=2000)'))
yeah, lets eliminate for now.

2023-05-30 11:29 UTC, jonathon-love commented on R/conttables.b.R
> +                        fish <- try(stats::fisher.test(mat, alternative=Ha, simulate.p.value=TRUE), silent=TRUE)
oh ok, if it's not used, then i agree it isn't necessary

2023-05-31 00:42 UTC, jonathon-love commented
merged. thanks mz!

2023-05-31 00:42 UTC, closed without merging