CI: Install jmvcore from github
jamovi/jmv pull request #391
Opened 2023-08-01 04:45 UTC by jonathon-love

2023-08-01 10:14 UTC, raviselker requested changes
This is indeed a nicer way to install `jmvcore` from github. Besides the requested change it looks good!

2023-08-01 10:14 UTC, raviselker commented on .github/workflows/R-CMD-check.yaml
> +#          Rscript -e "remotes::install_github('jamovi/jmvcore')"
Could you remove this commented out code, as it has no function anymore

2023-08-01 11:27 UTC, raviselker commented on .github/workflows/R-CMD-check.yaml
> +        run: sudo apt install -y protobuf-compiler libprotobuf-dev libprotoc-dev
Why is this necessary?

2023-08-02 01:09 UTC, shun2wang commented on .github/workflows/R-CMD-check.yaml
> +        run: sudo apt install -y protobuf-compiler libprotobuf-dev libprotoc-dev
This is needs by dependence of the `RProtoBuf ` packages (that needs by others) compiling to install on Linux. if dont have this will also failing the action.

2023-08-02 01:15 UTC, shun2wang commented on .github/workflows/R-CMD-check.yaml
> +        run: sudo apt install -y protobuf-compiler libprotobuf-dev libprotoc-dev
See https://github.com/shun2wang/jmv/actions/runs/5721838902 to learn more details.

2023-08-02 01:21 UTC, jonathon-love commented
thanks so much sw!

i'm going to close this PR, because i opened it ... can i get you to open the same PR :P

by having you open the PR, its implied consent to us incorporating these changes into the project.

with thanks

2023-08-02 01:21 UTC, closed without merging

2023-08-02 01:30 UTC, shun2wang commented
@jonathon-love Yes I agree to merge these commits, I signed the CLA 2 years ago didn't I? hahaha, could you please reopen this PR or i don't mind you use these commit into PRs you opened. 😀

2023-08-02 01:32 UTC, jonathon-love commented
haha, i know! :)

but can i get you to open the PR?

2023-08-02 01:33 UTC, shun2wang commented
I I don't have permission to open this PR but I can open new one for it.

2023-08-02 01:33 UTC, jonathon-love commented
yeah, new one would be perfect. it should only be a couple of clicks.

with thanks