Added post-hoc table for residuals
jamovi/jmv pull request #419
Opened 2024-12-03 23:56 UTC by MAgojam

## Summary of Changes

This PR introduces a dedicated **post-hoc residuals table (phoc)** to complement the contingency table analyses.
Alongside the primary frequency tables and their associated statistics, the phoc table provides a richer diagnostic layer by presenting an array of residuals at the cell level.

### Key Features:

* **New phoc table:** Adds a post-hoc overview of cell-level residuals (Unstandardized, Pearson, Standardized, and Adjusted).
* **Residual Types:**
  * **Unstandardized:** Raw differences between observed and expected counts.
  * **Pearson:** Residuals scaled by the square root of the expected values.
  * **Standardized:** Residuals further normalized to account for row and column distributions, facilitating clearer interpretation.
  * **Adjusted:** Residuals derived from a Poisson GLM, providing an additional layer of refinement by incorporating row and column effects.
* **Integration:** Computations are seamlessly integrated into the existing workflow. A chi-square test and a GLM fit are performed internally, and their results are then rendered in the phoc table.
* **Enhanced Testing:** The `testconttables.R` file has been updated with new tests, ensuring the accuracy and consistency of each residual type.

### User Benefit:

This enhancement offers a deeper analytical perspective, enabling users to pinpoint meaningful discrepancies and interpret their contingency table results with greater clarity and nuance.

2024-12-04 11:58 UTC, raviselker requested changes
Hi @MAgojam,
Awesome work, i think this will make a great addition to the contingency table analysis! Overall, I think this PR is already in a pretty good state, but I've added some comments on where I think improvements can be made. Thanks for your work!
Cheers,
Ravi

2024-12-04 11:58 UTC, raviselker commented on jamovi/conttables.u.yaml
> +              - type: LayoutBox
I think it would be nice if the post hoc tests are in its own CollapseBox so that it's in line with the post hoc tests in the anova.

2024-12-04 11:58 UTC, raviselker commented on jamovi/conttables.u.yaml
> +                    label: Post-hoc
We do labels in title case. Also, try to keep labels consistent with other analyses. In the anova it's called `Post Hoc Tests`.

2024-12-04 11:58 UTC, raviselker commented on jamovi/conttables.r.yaml
> +    - name: phoc
The post hoc table in anova is called `postHoc` (see https://github.com/jamovi/jmv/blob/9643e88c4eb8a205001b448f1051d4acf0dac619/jamovi/ancova.r.yaml#L165), please change it so that it's consistent with that

2024-12-04 11:58 UTC, raviselker commented on jamovi/conttables.r.yaml
> +      title: Post-hoc (residuals)
I would just call it `Post Hoc Tests` (you can see that it's residuals from the table)
```suggestion
      title: Post Hoc Tests
```

2024-12-04 11:58 UTC, raviselker commented on jamovi/conttables.r.yaml
> +        - resA
You probably don't need to clear the table when these options change as fitted model should stay the same

2024-12-04 11:58 UTC, raviselker commented on jamovi/conttables.r.yaml
> +
```suggestion
```

2024-12-04 11:58 UTC, raviselker commented on jamovi/conttables.r.yaml
> +      description: a table of residuals
```suggestion
      description: a table of post-hoc residuals
```

2024-12-04 11:58 UTC, raviselker commented on jamovi/conttables.r.yaml
> +    - name: phoc
Can you move this table above the `barPlot`? I think it's nicer if the plots are shown at the bottom of the results.

2024-12-04 11:58 UTC, raviselker commented on R/conttables.b.R
> +        .runPhocTab=function(data=data) {
Can you call it `.populatePostHocTable` to make it consistent with other analyses? See for instance the linear regression (https://github.com/jamovi/jmv/blob/master/R/linreg.b.R) for an example on naming conventions.

2024-12-04 11:58 UTC, raviselker commented on R/conttables.b.R
> +                levels <- base::levels(data[[colVarName]])
You don't have call functions from the `base` namespace explicitly (otherwise you'd have to `base::` every base function that you use. So this can just be:
 ```suggestion
                 levels <- levels(data[[colVarName]])
```

2024-12-04 11:58 UTC, raviselker commented on R/conttables.b.R
> +                    vPh <- visiblePh[j]
So now the `residuals` column is not visible if **only** the unstandardized residuals are checked. I think it's nice to not show the column when only one type of `residuals` is checked no matter what the type is. However, than you do need to add some information (probably to the table title) that you are showing a specific type of post hoc test. So for instance, for the unstandardized residuals I would expect a title such as `Post Hoc Tests (Unstandardized Residuals).

2024-12-04 11:58 UTC, raviselker commented on R/conttables.b.R
> +                                                 .('Pearson Residuals: (Observed - Expected) / sqrt(Expected).'))
I don't think these footnotes add much as it's very easy to look up what each specific residual means. Moreover, these footnotes would be more general information that wouldn't only show up when a value is `> 2`.

2024-12-04 11:58 UTC, raviselker commented on R/conttables.b.R
> +                                phoc$addFormat(rowNo=freqRowNo, col=colName, Cell.NEGATIVE)
At the moment, it's not really clear what it means if a value turns red. I think it would be good to add a general table note if any of the values become red so that users know what this indicates.

Maybe it would also be nice to make the highlighting of values an option (similar to how it's done in CFA):
<img width="302" alt="Screenshot 2024-12-04 at 12 53 40" src="https://github.com/user-attachments/assets/e3d74635-87eb-4f44-b387-d8f57a0593ce">

2024-12-04 11:58 UTC, raviselker commented on tests/testthat/testconttables.R
> +    # Test residuals phoc tables
Appreciate the addition of test cases! Are there any alternative scenarios that should be tested?

2024-12-13 14:00 UTC, MAgojam commented on tests/testthat/testconttables.R
> +    # Test residuals phoc tables
Yes, I updated to also check for a layer variable

2024-12-13 14:00 UTC, MAgojam commented
Hi @raviselker,

Thank you for your feedback on my PR. I've carefully reviewed your comments and have made the necessary adjustments. I've also conducted additional testing to ensure that the changes work as intended.

Please let me know if you would like me to provide any further details.

Regards,
Maurizio

2024-12-13 14:02 UTC, MAgojam commented on R/conttables.b.R
> +                                phoc$addFormat(rowNo=freqRowNo, col=colName, Cell.NEGATIVE)
Now there is like you suggested

2024-12-13 14:04 UTC, MAgojam commented on R/conttables.b.R
> +                                                 .('Pearson Residuals: (Observed - Expected) / sqrt(Expected).'))
You're right, I deleted them.

2024-12-13 14:06 UTC, MAgojam commented on R/conttables.b.R
> +                    vPh <- visiblePh[j]
I did as you suggested and you will tell me if it can work like this.

2024-12-13 14:09 UTC, MAgojam commented on R/conttables.b.R
> +                levels <- base::levels(data[[colVarName]])
I did as you suggested, but since it was the same in the other functions that I did not touch and I had followed the same calling method.

2024-12-13 14:21 UTC, MAgojam commented on jamovi/conttables.r.yaml
> +        - resA
Yes you are right, so I removed the possibility of a `clearWith` for the `postHoc` table, because it would lead to an unnecessary step from the `.init()` function, where it would be rebuilt even when the values ​​of the residues have not been modified.

2024-12-13 14:23 UTC, MAgojam commented on jamovi/conttables.r.yaml
> +      title: Post-hoc (residuals)
Done

2024-12-13 14:24 UTC, MAgojam commented on jamovi/conttables.u.yaml
> +              - type: LayoutBox
Yes this is a great suggestion, which I have applied in this update.

2024-12-13 14:27 UTC, MAgojam commented on jamovi/conttables.u.yaml
> +                    label: Post-hoc
I know, I did it and I will be more careful about these aspects next time.

2024-12-13 14:27 UTC, MAgojam commented on jamovi/conttables.r.yaml
> +    - name: phoc
Done.

2025-01-02 19:32 UTC, MAgojam commented on R/conttables.b.R
> +        .runPhocTab=function(data=data) {
Done.

2025-01-02 19:32 UTC, MAgojam commented on jamovi/conttables.r.yaml
> +    - name: phoc
Done.

2025-01-02 19:34 UTC, MAgojam commented on jamovi/conttables.r.yaml
> +      description: a table of residuals
Done.

2025-01-22 13:21 UTC, raviselker approved these changes
The rework looks good! I added one question, but that's my only comment

2025-01-22 13:21 UTC, raviselker commented on jamovi/conttables.a.yaml
> +
Is there a reason that it's not possible to highlight the unstandardized residuals?

2025-01-23 00:14 UTC, MAgojam commented on jamovi/conttables.a.yaml
> +
The unstandardized residuals can technically be highlighted, but they are generally less informative in the context of contingency tables.
Unlike standardized residuals, unstandardized residuals are raw differences between observed and expected frequencies and do not account for the variability of the data or the sample size. Highlighting them may lead to misleading interpretations, as larger residuals could simply reflect larger expected frequencies rather than significant deviations.

If highlighting unstandardized residuals is critical for a specific analysis, it can be implemented, but care should be taken to clarify their limitations and ensure they are not misinterpreted. Alternatively, standardized residuals are typically used for highlighting because they normalize these differences, making them easier to compare across cells and interpret within the context of statistical significance.

I owe you one, raviselker!
Thanks for taking the time to review this PR.

2025-01-23 00:15 UTC, jonathon-love commented on jamovi/conttables.a.yaml
> +
what does "highlight" mean in this context?

2025-01-23 15:02 UTC, MAgojam commented on jamovi/conttables.a.yaml
> +
The `a.yaml `file currently defines highlighting thresholds only for three residue types: P, S, and A.
 This means that unstandardized residuals are not explicitly considered for highlighting.
 I previously explained the rationale for excluding unstandardized residuals.
 However, if you would like to include them for completeness, I can readily add the necessary configuration to the `a.yaml` file.

2025-01-26 00:16 UTC, merged